### ISSUE TITLE
Fix __init__ method of Bright

### ISSUE THREAD

**Issue by Kazy** [brightforme/python-bright#3]
A couple of remarks:
- We should use positional arguments when there is a default value (for `host`, `use_ssl`). We should also use normal arguments for the required one: `client_id` and `scopes`.
- https://github.com/brightforme/python-bright/blob/master/bright/bright.py#L22 This should be put on the line above, before we define the scheme. `use_ssl` isn't even needed as an object member, since we're only using its value to define the scheme.

**Comment by mekza** [comment]
The use_ssl thing is useless because OAuth 2.0 requires SSL, it should be removed.
